name: wrap_it_up
description: When someone takes too long to finish up, open this app and show them. Whats in your head.

dependencies:
  shared_preferences: "^0.2.5"
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true